apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: 891377396516.dkr.ecr.eu-central-1.amazonaws.com/hivemind_app_repo:latest
          ports:
            - containerPort: 8080
