name: CI/CD

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Build
        run: go build -o greeter greeter.go

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-aws-region

      - name: Login to Amazon ECR
        id: login-ecr
        run: aws ecr get-login-password --region your-aws-region | docker login --username AWS --password-stdin your-aws-account-id.dkr.ecr.your-aws-region.amazonaws.com

      - name: Tag Docker image
        run: docker tag your-docker-image:latest your-aws-account-id.dkr.ecr.your-aws-region.amazonaws.com/your-repository-name:latest

      - name: Push Docker image to ECR
        run: docker push your-aws-account-id.dkr.ecr.your-aws-region.amazonaws.com/your-repository-name:latest
